# Generated by Django 6.1 on 2026-08-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
