# Generated by Django 6.1 on 2026-09-10 12:37

from django.db import migrations, models


def backfill_total_paid(apps, schema_editor):
    Booking = apps.get_model('events', 'Booking')

    for booking in Booking.objects.select_related('event').iterator():
        booking.total_paid = booking.event.price * booking.quantity
        booking.save(update_fields=['total_paid'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_booking_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_paid',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_total_paid,
            migrations.RunPython.noop,
        ),
    ]