# Generated by Django 6.1 on 2026-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_price_event_event_price_gt_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('requires_action', 'Requires action'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20, null=True),
        ),
    ]
