# Generated by Django 6.1 on 2026-09-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_booking_refund_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutResolution',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'stripe_session_id',
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    'stripe_refund_id',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    'reason',
                    models.CharField(
                        choices=[
                            ('missing_user', 'Booking user unavailable'),
                            ('unavailable_event', 'Event unavailable'),
                            ('started_event', 'Event already started'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'refund_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('pending', 'Pending'),
                            ('requires_action', 'Requires action'),
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                            ('canceled', 'Canceled'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='checkout_resolutions',
                        to='events.event',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='checkout_resolutions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
